name: Publish Docker image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: corentingarcia/lecointre-balance
        username: corentingarcia
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: corentingarcia
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        repository: corentingarcia/lecointre-balance
        tag_with_ref: true
        add_git_labels: true
        push: ${{ github.ref == 'refs/heads/master' }}
