name: Publish Docker image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: corentingarcia/lecointre-balance
        username: corentingarcia
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Publish to Github Registry
      uses: matootie/github-docker@v2.0.0
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        imageName: corentingarcia/lecointre-balance
        username: corenting
